version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: Taller
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "3311:3306"
    volumes:
      - ./dbTaller:/var/lib/mysql
    networks:
      - mi_red

    restart: always

networks:
  mi_red:
    name: redTaller # Nombre real de la red
